#!/usr/bin/env python3

import shutil
import json

path = ["/"]

def stat(path):
    u = shutil.disk_usage(path)

if __name__ == '__main__':
    d={}
    for p in path:
        u=shutil.disk_usage(p)
        d[p]={
            "total":u.total, 
            "used":u.used, 
            "free":u.free
        }
j = json.dumps(d, indent=4,
    sort_keys=True, ensure_ascii=False, separators=(",", ": "))
print("Content-Type: application/json")
print()
print(j)

